//
//  VehicleLocationOperation.m
//  Buster
//
//  Created by andyshep on 11/14/10.
//
//  Copyright (c) 2010 Andrew Shepard
// 
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

#import "VehicleLocationOperation.h"


@implementation VehicleLocationOperation

@synthesize vehicleId, routeNumber, epochTime;

#pragma mark -
#pragma mark Vehicle Locations Processing

- (void)consumeData {
    
    [super consumeData];
    
    // get out now if there was any error generated by the superclass
    if (error_) return;
	
    SMXMLDocument *xml = [SMXMLDocument documentWithData:consumedData error:&error_];
    
    if (!error_) {
        
        NSMutableDictionary *vehicleLocation = [NSMutableDictionary dictionaryWithCapacity:3];
        
        for (SMXMLElement *vehicleElement in [xml.root childrenNamed:@"vehicle"]) {
            NSString *currentVehicleId = [vehicleElement attributeNamed:@"id"];

            if ([currentVehicleId compare:vehicleId] == 0) {
                // found a matching vehicle id so 
                // the vehicle we want is currently vehicleElement
                
                NSString *_vehicleId = [vehicleElement attributeNamed:@"id"];
                NSString *_latitude = [vehicleElement attributeNamed:@"lat"];
                NSString *_longitude = [vehicleElement attributeNamed:@"lon"];
                
                NSLog(@"found vehicle %@ at %@, %@", _vehicleId, _latitude, _longitude);
                
                [vehicleLocation setObject:_longitude forKey:@"longitude"];
                [vehicleLocation setObject:_latitude forKey:@"latitude"];
                
                consumedData = vehicleLocation;
            }
        }
    }
}

@end
